### ISSUE TITLE
Add 4 different DSA codes

### ISSUE THREAD

**Issue by ashish2675** [ashish2675/100DaysOfCode#1]

**Comment by YashBajpaiGITHUB** [comment]
Sir please assign me this issue. Also tell any particular methodology to follow.

**Comment by ashish2675** [comment]
@YashBajpaiGITHUB I have assigned the issue to you. Its for your learning so add a valid code of DSA in the repo. Happy Coding🧑‍💻

**Comment by YashBajpaiGITHUB** [comment]
Sir it should be  done in Java only or can I do in C? I mistakenly unassigned. Please reassign.

**Comment by ashish2675** [comment]
> Sir it should be done in Java only or can I do in C? I mistakenly unassigned. Please reassign.

Any language works. This is for your benefit to open source contribution
