### ISSUE TITLE
Add any 4 different leetcode answers in leet file 

### ISSUE THREAD

**Issue by ashish2675** [ashish2675/100DaysOfCode#3]

**Comment by ShubhamShakyawal** [comment]
Hi @ashish2675 , I want to contribute in this. Please Assign me.

**Comment by ashish2675** [comment]
> Hi @ashish2675 , I want to contribute in this. Please Assign me.

I have assigned you the issue. Happy Coding🧑‍💻

**Comment by Jilesh980** [comment]
Hi @ashish2675 i have created 4 files of Leetcode solution can you please accept the pull request. Thank you

**Comment by ShubhamShakyawal** [comment]
@ashish2675 A Pull Request https://github.com/ashish2675/100DaysOfCode/pull/12 has been created for this. Please do Check.
